global:
  environment: prod
backend:
  replicaCount: 3
  image: { tag: prod }
  env:
    DATABASE_HOST: cms-prod.abcdefgh.ap-south-1.rds.amazonaws.com
  autoscaling:
    minReplicas: 3
    maxReplicas: 10
frontend:
  replicaCount: 3
  image: { tag: prod }
  autoscaling:
    minReplicas: 3
    maxReplicas: 10
ingress:
  host: cms.example.com
