version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    image: rishavsingh09/cms-backend:local
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    ports: ["1337:1337"]
    depends_on: [postgres]

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    image: rishavsingh09/cms-frontend:local
    environment:
      NEXT_PUBLIC_API_URL: http://backend:1337
    ports: ["3000:3000"]
    depends_on: [backend]

volumes:
  pgdata:
