global:
  environment: dev
  imageRegistry: docker.io/rishavsingh09

backend:
  name: cms-backend
  image:
    repository: rishavsingh09/cms-backend
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 2
  service:
    type: ClusterIP
    port: 1337
  resources:
    requests: { cpu: 100m, memory: 256Mi }
    limits:   { cpu: 500m, memory: 512Mi }
  env:
    DATABASE_HOST: cms-postgres
    DATABASE_PORT: "5432"
    DATABASE_NAME: strapi
    DATABASE_USERNAME: strapi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70

frontend:
  name: cms-frontend
  image:
    repository: rishavsingh09/cms-frontend
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 2
  service:
    type: ClusterIP
    port: 3000
  resources:
    requests: { cpu: 100m, memory: 256Mi }
    limits:   { cpu: 500m, memory: 512Mi }
  env:
    NEXT_PUBLIC_API_URL: http://cms-backend:1337
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: nginx
  host: cms.dev.example.com
  tls:
    enabled: true
    secretName: cms-tls
